# Usa la imagen oficial de Node
FROM node:18

# Directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia archivos de Yarn y dependencias
COPY package.json yarn.lock ./

# Instala las dependencias dentro del contenedor
RUN yarn install

# Copia el resto del código de la app
COPY . .

# Expone el puerto que usa NestJS
EXPOSE 3000

# Comando por defecto para iniciar en modo desarrollo
CMD ["yarn", "start:dev"]
